openapi: '3.0.2'
info:
  title: API Payment Gateway
  description:  OPEN API for Payment Gateway 
  contact:
    name: Si-Bagus
    email: SiBagus@gmail.com
  version: '1.0'
servers:
  - url: https://{environment}.test/v1
    description: Open API Payment Gateway servers
    variables:
      environment:
        default: development
        description: server environment
        enum:
          - "development"
          - "production" 
  - url: https://{environment}.url_merchant/payment
    description: Open API Payment Gateway server
    variables:
      environment:
        default: development
        description: server environment
        enum:
          - "development"
          - "production"
     
paths:
  /notifications:
    post:
      tags:
        - payment
        - notification
      summary: post notification payment
      description: notification payment status 
      requestBody:
        content:
          aplication/json:
            schema:
              type: object
              properties:
                  request_id:
                    description: request description
                    type: string
                    maxLength: 50
                    example: Payment Notification
                  trx_id:
                    description: transaction id (issued/generated by faspay)
                    type: number
                    maxLength: 16
                    example: 3183540500001172
                  merchant_id:
                    description: merchant code
                    type: number
                    maxLength: 16
                    example: 31835
                  merchant:
                    description: merchant name
                    type: string
                    maxLength: 32
                    example: Panin Asset Management
                  bill_no:
                    description: order number
                    type: string
                    maxLength: 32
                    example: 220171004154635022158001
                  payment_reff:
                    type: string
                    maxLength: 32
                    example: null
                  payment_date:
                    description: customer payment date
                    type: string
                    example: 2017-10-04 15:46:35
                  payment_status_code:
                    description: payment status code
                    type: string
                    maxLength: 1
                    enum:
                      - '0': unprocessed
                      - '1': in process
                      - '2': payment success
                      - '3': payment failed
                      - '4': payment reversal
                      - '5': no bill found
                      - '7': payment expired
                      - '8': payment cancelled
                      - '9': unknown 
                    example: 2
                  payment_status_desc:
                    description: payment description
                    type: string
                    maxLength: 32
                    example: Payment Sukses
                  bill_total:
                    description: bill total of transaction
                    type: number
                    example: 5000000
                  payment_total:
                    description: payment total of transaction
                    type: number
                    example: 5000000
                  payment_channel_uid:
                    description: payment channel code
                    type: number
                    example: 402
                  payment_channel:
                    description: payment channel description
                    type: string
                    maxLength: 32
                    example: Permata Virtual Account
                  signature:
                    description: Sha1(md5(user_id+password + bill_no + payment_status_code))
                    type: string
                    example: 075c4983ba9883d41e1b3eab0de580dfc73d875b
        required: true
      responses:
        '200':
          description: success
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  trx_id:
                    description: transaction id
                    type: number
                    maxLength: 16
                  merchant_id:
                    description: Channel Code From Faspay
                    type: number
                    maxLength: 15
                  bill_no:
                    description: order number
                    type: string
                    maxLength: 32
                  response_code:
                    description: response code
                    type: string
                    maxLength: 2
                  response_desc:
                    description: response description
                    type: string
                    maxLength: 50
                  response_date:
                    description: response date
                    type: string
              
                
                    

  /va-static/inquiry-payment:
    get:
      tags:
        - payment
        - virtual account
      summary: get virtual account
      description:  get virtual account number for customer
      parameters:
        - name: VA
          description: virtual account number
          in: query
          schema:
            type: string
        - name: signature
          description:  sha1(md5($user_id.$password.$va_number));
          schema:
            type: string
          in: query
        - name: type
          description: type = inquiry
          schema:
            type: string
          in: query
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    description: VA static responses
                    type: string
                    maxLength: 50
                  VA_number:
                    description: virtual account number
                    type: number
                    maxLength: 16
                  ammount:
                   description: ammount
                   type: number
                  cust_name:
                    description: ID customer number
                    type: string
                    maxLength: 50
                  response_code:
                    description: response status code
                    type: string
                    maxLength: 2
                    enum:
                      - 00 : success
                      - 01 : failed
              example:
                values:
                  response: VA Static Response
                  VA_number: 864116202100000
                  ammount: 100000
                  cust_name: suyanto
                  response_code: 00
          



  /va-static/inquiry-transaction:
    get:
      tags:
        - payment
        - virtual ammount
      summary: get virtual ammount 
      description: get virtual ammount number for customer
      parameters:
        - name: VA_number
          description: virtual account number
          in : query
          schema:
            type: string
        - name: signature
          description: sha1(md5($user_id.$password.$va_number));
          in: query
          schema:
            type: string
        - name: type
          description: type = payment
          in : query
          schema:
            type: string
        - name: trx_uid
          description: Unix transaction number on Faspay
          in: query
          schema:
            type: string
        - name: ammount
          description: Amount transaction
          in: query
          schema:
            type: string
 
      responses:
        '200':
          description: success
          content:
            aplication/json:
              schema:
                type: object
                properties:
                  response:
                    description: VA static responses
                    type: string
                    maxLength: 50
                  VA_number:
                    description: virtual account number
                    type: number
                    maxLength: 16
                  ammount:
                   description: ammount
                   type: number
                  cust_name:
                    description: ID customer number
                    type: string
                    maxLength: 50
                  response_code:
                    description: response status code
                    type: string
                    maxLength: 2
                    enum:
                      - 00 : success
                      - 01 : failed
                example:
                  values:
                    response: VA Static Response
                    VA_number: 864116202100000
                    ammount: 100000
                    cust_name: suyanto
                    response_code: 00


      

   
  

